project:
  type: website
  output-dir: docs

website:
  title: "finedtech"
  navbar:
    right:
      - icon: github
        href: https://github.com/bionicturtle
      - icon: instagram
        href: https://www.instagram.com/davidharper2/ 
format:
  html:
    theme: [sandstone, custom.scss]
    css: styles.css

editor: visual











